# ── ADC ───────────────────────────────────────────────────────────────────────
CONFIG_GPIO=n
CONFIG_NRFX_GPIOTE=y
CONFIG_NRFX_SAADC=y
CONFIG_NRFX_TIMER2=y
CONFIG_NRFX_DPPI=y


# ── POWER MANAGEMENT ──────────────────────────────────────────────────────────
CONFIG_PM_DEVICE=y
CONFIG_PM_DEVICE_RUNTIME=y
